//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Data.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int ShopId { get; set; }
        public string NameOfDay { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int Id { get; set; }
    
        public virtual Shops Shops { get; set; }
    }
}
